set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L

set columns=160
set lines=50

if has('win32')
    set guifont=Consolas:h10
else
    set guifont=DejaVu\ Sans\ Mono\ 10
endif

highlight Normal guibg=gray16
