set guioptions-=m
set guioptions-=T
set guioptions-=r
set guioptions-=L

set columns=160
set lines=40

if has('win32')
    set guifont=Hack:h10,Consolas:h10
else
    set guifont=Hack,DejaVu\ Sans\ Mono\ 10
endif
