Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add:
      - bugprone-*
      - clang-analyzer-*
      - concurrency-*
      - cppcoreguidelines-*
      - hicpp-*
      - misc-*
      - modernize-*
      - performance-*
      - portability-*
      - readability-*
    Remove:
      - cppcoreguidelines-avoid-magic-numbers
      - modernize-use-trailing-return-type
      - readability-magic-numbers
