CompileFlags:
  Remove:
    - -fno-canonical-system-headers
Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add:
      - bugprone-*
      - cert-*
      - clang-analyzer-*
      - concurrency-*
      - cppcoreguidelines-*
      - hicpp-*
      - llvm-*
      - misc-*
      - modernize-*
      - performance-*
      - portability-*
      - readability-*
    Remove:
      - bugprone-easily-swappable-parameters
      - cert-err58-cpp
      - cppcoreguidelines-avoid-c-arrays
      - cppcoreguidelines-avoid-magic-numbers
      - cppcoreguidelines-avoid-non-const-global-variables
      - cppcoreguidelines-macro-usage
      - cppcoreguidelines-non-private-member-variables-in-classes
      - cppcoreguidelines-pro-bounds-array-to-pointer-decay
      - cppcoreguidelines-pro-bounds-constant-array-index
      - cppcoreguidelines-pro-bounds-pointer-arithmetic
      - cppcoreguidelines-pro-type-const-cast
      - cppcoreguidelines-pro-type-reinterpret-cast
      - cppcoreguidelines-pro-type-vararg
      - hicpp-avoid-c-arrays
      - hicpp-explicit-conversions
      - hicpp-named-parameter
      - hicpp-no-array-decay
      - hicpp-signed-bitwise
      - hicpp-uppercase-literal-suffix
      - hicpp-vararg
      - misc-non-private-member-variables-in-classes
      - modernize-avoid-c-arrays
      - modernize-use-nodiscard
      - modernize-use-trailing-return-type
      - readability-function-cognitive-complexity
      - readability-identifier-length
      - readability-implicit-bool-conversion
      - readability-magic-numbers
      - readability-named-parameter
      - readability-qualified-auto
      - readability-uppercase-literal-suffix
    CheckOptions:
      misc-non-private-member-variables-in-classes.IgnorePublicMemberVariables: true
