PROMPT_COMMAND=__prompt_command

__prompt_command() {
    local EXIT="$?"

    local CYAN='\[\e[36;1m\]'
    local RED='\[\e[31;1m\]'
    local GREEN='\[\e[32;1m\]'
    local END='\[\e[0m\]'
    PS1=''

    PS1+="\n"
    if [ $EXIT != 0 ]; then
        PS1+="${RED}[${EXIT}]${END} "
    fi
    PS1+="${CYAN}\u@\h \w${END}\n"
    PS1+="${GREEN}\$${END} "
}

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
