#!/bin/sh

REPO_URL='git@github.com:snailbaron/.dotfiles.git'
ALIAS_COMMAND="alias config 'git --git-dir \"$HOME/.dotfiles\" --work-tree \"$HOME\"'"

git clone --bare "$REPO_URL" "$HOME/.dotfiles"
config config status.showUntrackedFiles no
echo "$ALIAS_COMMAND" >> ~/.bashrc
$ALIAS_COMMAND
