#!/bin/sh -e

# colors
_rs="\[\e[1;31m\]"
_gs="\[\e[1;32m\]"
_ys="\[\e[1;33m\]"
_cs="\[\e[1;36m\]"
_end="\[\e[0m\]"

_prompt_nonzero_return_code() {
    code=$?
    if [ $code -ne 0 ]; then
        echo -n " ${code}"
    fi
}

_prompt_git_branch() {
    gitdir=""

    dir=$(pwd)
    while [ "$dir" != "/" ]; do
        if [ -d "$dir/.git" ]; then
            gitdir="$dir/.git"
            break
        fi
        dir=$(dirname "$dir")
    done

    if [ -z "$gitdir" ]; then
        return
    fi

    if [ ! -f "$gitdir/HEAD" ]; then
        return
    fi

    echo -n " "
    head_content=$(cat "$gitdir/HEAD")
    head_content="${head_content#ref: }"
    head_content="${head_content#refs/heads/}"
    echo "$head_content"
}

_prompt_debian_chroot_prefix='${debian_chroot:+($debian_chroot)}'
_prompt_base_part="$_ys\u$_end ${_gs}DEV$_end $_cs\w$_end"

PS1="\n${_prompt_debian_chroot_prefix}${_prompt_base_part}$_rs\$(_prompt_nonzero_return_code)$_end$_gs\$(_prompt_git_branch)$_end\n$_gs\$$_end "
