#!/usr/bin/env bash

error() {
  >&2 echo "$@"
}

[ -f ~/.fzf.bash ] && source ~/.fzf.bash

co() {
    if [ -n "$*" ]; then
        error "co does not accept arguments"
        return 1
    fi

    if ! >/dev/null command -v git; then
        error "git command not found"
        return 1
    fi

    if [ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" != "true" ]; then
        error "not inside a git work tree"
        return 1
    fi

    result=$(git branch | fzf)
    branch="${result:2}"
    git checkout "$branch"
}
